# Generated by Django 5.0.2 on 2025-03-05 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Humidity cannot be less than 0%'), django.core.validators.MaxValueValidator(100, message='Humidity cannot be more than 100%')]),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-100, message='Temperature cannot be less than -100°C'), django.core.validators.MaxValueValidator(100, message='Temperature cannot be more than 100°C')]),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['city'], name='weather_api_city_77795d_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['-timestamp'], name='weather_api_timesta_6824c7_idx'),
        ),
    ]
