# Generated by Django 5.0.2 on 2025-03-05 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_alter_weather_humidity_alter_weather_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='clouds',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-100, message='Feels like temperature cannot be less than -100°C'), django.core.validators.MaxValueValidator(100, message='Feels like temperature cannot be more than 100°C')]),
        ),
        migrations.AddField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='weather',
            name='sunrise',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='sunset',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_direction',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['temperature'], name='weather_api_tempera_2a8430_idx'),
        ),
    ]
