# Generated by Django 5.0.2 on 2025-03-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_weather_clouds_weather_feels_like_weather_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weather',
            name='weather_api_tempera_2a8430_idx',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='clouds',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='feels_like',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='sunset',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temp_min',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_speed',
        ),
    ]
